places=["maldives", "dubai", "scandinavia", "moscow", "iceland", "africa"]
print(places)
print(sorted(places))
print(places)
print(sorted(places, reverse=True))
print(places)
places.reverse()
print(places)
places.reverse()
print(places)
places.sort()
print(places)
places.sort(reverse=True)
print(places)
print(f"Here's the number of places I want to go to: {len(places)}.")
